# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-25 02:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='confirm_pw',
            new_name='confirm_password',
        ),
    ]
