# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-24 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_auto_20180123_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='houses.Base')),
                ('title', models.CharField(max_length=254)),
                ('description', models.TextField(default='A Class')),
                ('members', models.ManyToManyField(to='houses.Student')),
            ],
            bases=('houses.base',),
        ),
    ]
