# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-25 23:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt_review', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegUser',
            new_name='NewUser',
        ),
    ]
